### ISSUE TITLE
error using map studio

### ISSUE THREAD

**Issue by wwwronin** [jetelain/ArmaRealMap#10]
I'm trying to use map studio to generate . I got some errors here:
** 'Roads.Merge' done in 8218 msec
**** Begin 'Roads.IgnoreSmall'
** 'Roads.IgnoreSmall' done in 0 msec
Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'MaxDegreeOfParallelism')
   at System.Threading.Tasks.ParallelOptions.set_MaxDegreeOfParallelism(Int32 value)
   at SixLabors.ImageSharp.Advanced.ParallelRowIterator.IterateRowIntervals[T](Rectangle rectangle, ParallelExecutionSettings& parallelSettings, T& operation)
   at SixLabors.ImageSharp.Drawing.Processing.Processors.Drawing.FillProcessor`1.OnFrameApply(ImageFrame`1 source)
   at SixLabors.ImageSharp.Processing.Processors.ImageProcessor`1.SixLabors.ImageSharp.Processing.Processors.IImageProcessor<TPixel>.Execute()
   at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor, Rectangle rectangle)
   at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor)
   at SixLabors.ImageSharp.Drawing.Processing.FillExtensions.Fill(IImageProcessingContext source, DrawingOptions options, IBrush brush)
   at SixLabors.ImageSharp.Drawing.Processing.FillExtensions.Fill(IImageProcessingContext source, IBrush brush)
   at GameRealisticMap.Arma3.Imagery.IdMapRenderBase`1.<Render>b__4_0(IImageProcessingContext d) in \TerrainTool\ArmaRealMap\GameRealisticMap.Arma3\Imagery\IdMapRenderBase.cs:line 39
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Configuration configuration, Action`1 operation)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Action`1 operation)
   at GameRealisticMap.Arma3.Imagery.IdMapRenderBase`1.Render(IArma3MapConfig config, IContext context) in \TerrainTool\ArmaRealMap\GameRealisticMap.Arma3\Imagery\IdMapRenderBase.cs:line 39
   at GameRealisticMap.Arma3.Imagery.ImagerySource.CreateIdMap() in \TerrainTool\ArmaRealMap\GameRealisticMap.Arma3\Imagery\ImagerySource.cs:line 26
   at GameRealisticMap.Arma3.GameEngine.ImageryCompiler.Compile(IArma3MapConfig config, IImagerySource source) in \TerrainTool\ArmaRealMap\GameRealisticMap.Arma3\GameEngine\ImageryCompiler.cs:line 53
   at GameRealisticMap.Arma3.Arma3MapGenerator.GenerateWrp(IProgressTask progress, IArma3MapConfig config, IContext context, ITerrainArea area, Arma3LayerGeneratorCatalog generators) in \
TerrainTool\ArmaRealMap\GameRealisticMap.Arma3\Arma3MapGenerator.cs:line 71
   at GameRealisticMap.Arma3.Arma3MapGenerator.GenerateWrp(IProgressTask progress, Arma3MapConfig a3config) in \TerrainTool\ArmaRealMap\GameRealisticMap.Arma3\Arma3MapGenerator.cs:line 40
   at GameRealisticMap.Studio.Modules.MapConfigEditor.ViewModels.MapConfigEditorViewModel.DoGenerateMap(IProgressTool progressTool) in \TerrainTool\ArmaRealMap\GameRealisticMap.Studio\Modules\MapConfigEditor\ViewModels\MapConfigEditorViewModel.cs:line 303
ERROR: Specified argument was out of the range of valid values. (Parameter 'MaxDegreeOfParallelism')
Task FAILED after 17.4 seconds

**Comment by jetelain** [comment]
Hi,
It looks like that ImageSharp have an issue with image size. 
I had a look to their source code, it computes `width * height` on a int. If you tried 400x400Km with a decent resolution like 5m/px,  `width * height` will be equal to `7 530 086 400`  which overflows `int.MaxValue => 2 147 483 647`. Due to this limitation, image width is limited to `Math.Sqrt(int.MaxValue) => 46340`. So you should set resolution to 9 m/px until I add the system able to split very large images. 
I will also submit a merge request on ImageSharp to compute `width * height` on a long to circumvent the issue (and allow draw operation on large pictures). But not sure that images that are larger than 8 GiB will be seen as legitimate use case.

**Comment by wwwronin** [comment]
I think split method may be better. So when will you add that system .

**Comment by jetelain** [comment]
Should have been fixed with the HugeImage system
