### ISSUE TITLE
TopologyException in PlaceBuildings

### ISSUE THREAD

**Issue by jetelain** [jetelain/ArmaRealMap#100]
```json
{"Resolution":1,"FakeSatBlend":0.5,"GridCellSize":5,"GridSize":8192,"Center":"41.950651568348626, 9.175354666423724","AssetConfigFile":"builtin:CentralEurope.grma3a"}
```

```
2023-08-20 15:57:30.2138|NetTopologySuite.Geometries.TopologyException: found non-noded intersection between LINESTRING(37019.59765625 8042.65283203125, 37016.84375 8033.7060546875) and LINESTRING(37016.84375 8033.703125, 37017.26953125 8037.02978515625) [ (37016.84439186801, 8033.708139961899, NaN) ]
   at NetTopologySuite.Operation.Overlay.Snap.SnapIfNeededOverlayOp.GetResultGeometry(SpatialFunction opCode)
   at GameRealisticMap.Arma3.ManMade.BuildingGenerator.<>c__DisplayClass10_1.<RealBoxAdjustedToRoad>b__6(TerrainPolygon p)
   at System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector)
   at System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector)
   at GameRealisticMap.Arma3.ManMade.BuildingGenerator.<>c__DisplayClass10_0.<RealBoxAdjustedToRoad>b__3(BoundingBox b)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at GameRealisticMap.Arma3.ManMade.BuildingGenerator.RealBoxAdjustedToRoad(List`1 roads, Vector2 size, BoundingBox box)
   at GameRealisticMap.Arma3.ManMade.BuildingGenerator.TryPlaceBuilding(List`1 buildings, List`1 roads, Building building, Single min, Single max)
   at GameRealisticMap.Arma3.ManMade.BuildingGenerator.Generate(IArma3MapConfig config, IContext context)
   at GameRealisticMap.Arma3.Arma3MapGenerator.<>c__DisplayClass11_0.<GetObjects>b__0(ITerrainBuilderLayerGenerator tb)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at GameRealisticMap.Arma3.GameEngine.WrpCompiler.Write(IArma3MapConfig config, ElevationGrid elevationGrid, ImageryTiler terrainTiler, IEnumerable`1 objects)
   at GameRealisticMap.Arma3.Arma3MapGenerator.GenerateWrp(IProgressTask progress, Arma3MapConfig config, IContext context, ITerrainArea area, Arma3LayerGeneratorCatalog generators)
   at GameRealisticMap.Arma3.Arma3MapGenerator.GenerateWrp(IProgressTask progress, Arma3MapConfig a3config)
   at GameRealisticMap.Arma3.Arma3MapGenerator.GenerateMod(IProgressTask progress, Arma3MapConfig a3config)
   at GameRealisticMap.Studio.Modules.MapConfigEditor.ViewModels.MapConfigEditorViewModel.DoGenerateMod(IProgressTaskUI task)
   at GameRealisticMap.Studio.Modules.Reporting.ViewModels.ProgressToolViewModel.DoRunTask(String name, Func`2 run)
```

The NaN is not normal, and likely cause by an earlier error.

Should use Clipper for intersection instead of NetTopologySuite, but this would required to create tests.

**Comment by jetelain** [comment]
The road polygon is considered invalid by NetTopologySuite, should simply use Clipper for that
