### ISSUE TITLE
On Generation of map "Func`2 run" missing closing statements/strings?

### ISSUE THREAD

**Issue by diveyez** [jetelain/ArmaRealMap#102]
** 'RawSatelliteImage.S2C' done in 00:00:47.3150801
Exception: System.Exception: Texture '' was not found, unable to generate fake satmap.
   at GameRealisticMap.Arma3.Imagery.FakeSatRender.GetBrush(TerrainMaterial material)
   at GameRealisticMap.Arma3.Imagery.FakeSatRender.<>c__DisplayClass4_0.<RenderSatOut>b__0(IImageProcessingContext d)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Configuration configuration, Action`1 operation)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Action`1 operation)
   at GameRealisticMap.Arma3.Imagery.FakeSatRender.RenderSatOut(IArma3MapConfig config, IContext context, Int32 size)
   at GameRealisticMap.Arma3.Imagery.SatMapRender.RenderSatOut(IArma3MapConfig config, IContext context, Int32 size)
   at GameRealisticMap.Arma3.Imagery.ImagerySource.CreateSatOut()
   at GameRealisticMap.Arma3.GameEngine.ImageryCompiler.CreateConfigCppImages(IGameFileSystemWriter gameFileSystemWriter, IArma3MapConfig config, IImagerySource source)
   at GameRealisticMap.Arma3.Arma3TerrainBuilderGenerator.ExportImagery(IProgressTask progress, Arma3MapConfig config, BuildContext context, String targetDirectory)
   at GameRealisticMap.Arma3.Arma3TerrainBuilderGenerator.GenerateFilesAsync(IProgressTask progress, Arma3MapConfig config, BuildContext context, ITerrainArea area, Arma3LayerGeneratorCatalog generators, String targetDirectory)
   at GameRealisticMap.Arma3.Arma3TerrainBuilderGenerator.GenerateTerrainBuilderFiles(IProgressTask progress, Arma3MapConfig a3config, String targetDirectory)
   at GameRealisticMap.Studio.Modules.MapConfigEditor.ViewModels.MapConfigEditorViewModel.DoGenerateTerrainBuilder(IProgressTaskUI task)
   at GameRealisticMap.Studio.Modules.Reporting.ViewModels.ProgressToolViewModel.DoRunTask(String name, Func`2 run)
ERROR: Texture '' was not found, unable to generate fake satmap.
Task FAILED after 55.9 seconds
ERROR: Texture '' was not found, unable to generate fake satmap.
Task FAILED after 55.9 seconds

I have a report file, where can I send it to you?

**Comment by jetelain** [comment]
Hi, this error may happen with custom assets if a texture is not specified in the "Ground materials" section. You may probably starts from the "CentralEurope" base asset config to ensure required elements are present. Current UI lacks input validation.
To send the error report you may join it to the issue, or contact me on the project Discord : https://discord.gg/9JTHHKWJPn
