### ISSUE TITLE
Error with Airport elevation generator

### ISSUE THREAD

**Issue by jetelain** [jetelain/ArmaRealMap#218]
Reported by Davidaf

```
Exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at GameRealisticMap.ManMade.Airports.AerowaysElevationProcessor.SmoothAerowaysWithinAirport(AirportAeroways airport, ElevationGrid grid) in D:\a\ArmaRealMap\ArmaRealMap\GameRealisticMap\ManMade\Airports\AerowaysElevationProcessor.cs:line 51
   at GameRealisticMap.ManMade.Airports.AerowaysElevationProcessor.ProcessStage1(ElevationGrid grid, IContext context) in D:\a\ArmaRealMap\ArmaRealMap\GameRealisticMap\ManMade\Airports\AerowaysElevationProcessor.cs:line 26
   at GameRealisticMap.ElevationModel.ElevationWithLakesBuilder.Build(IBuildContext context) in D:\a\ArmaRealMap\ArmaRealMap\GameRealisticMap\ElevationModel\ElevationWithLakesBuilder.cs:line 66
   at GameRealisticMap.BuildContext.GetData[T]() in D:\a\ArmaRealMap\ArmaRealMap\GameRealisticMap\BuildContext.cs:line 50
   at GameRealisticMap.Nature.BasicBuilderBase`1.GetPriority(IBuildContext context) in D:\a\ArmaRealMap\ArmaRealMap\GameRealisticMap\Nature\BasicBuilderBase.cs:line 24
   at GameRealisticMap.ManMade.Farmlands.OrchardBuilder.GetPriority(IBuildContext context) in D:\a\ArmaRealMap\ArmaRealMap\GameRealisticMap\ManMade\Farmlands\OrchardBuilder.cs:line 29
   at GameRealisticMap.Nature.PolygonBuilderBase.GetPolygons(IBuildContext context, IEnumerable`1 additionals) in D:\a\ArmaRealMap\ArmaRealMap\GameRealisticMap\Nature\PolygonBuilderBase.cs:line 23
   at GameRealisticMap.Nature.BasicBuilderBase`1.Build(IBuildContext context) in D:\a\ArmaRealMap\ArmaRealMap\GameRealisticMap\Nature\BasicBuilderBase.cs:line 37
   at GameRealisticMap.BuildContext.GetData[T]() in D:\a\ArmaRealMap\ArmaRealMap\GameRealisticMap\BuildContext.cs:line 50
   at GameRealisticMap.Arma3.Imagery.IdMapRenderBase`1.<>c__DisplayClass4_0.<Render>b__0(IImageProcessingContext d) in D:\a\ArmaRealMap\ArmaRealMap\GameRealisticMap.Arma3\Imagery\IdMapRenderBase.cs:line 59
   at HugeImages.Processing.ProcessingExtensions.<>c__DisplayClass0_0`1.<MutateAllAsync>b__0(IImageProcessingContext d) in D:\a\ArmaRealMap\ArmaRealMap\HugeImages\HugeImages\Processing\ProcessingExtensions.cs:line 15
   at HugeImages.Processing.ProcessingExtensions.MutateAllAsync[TPixel](HugeImage`1 image, Func`2 operation) in D:\a\ArmaRealMap\ArmaRealMap\HugeImages\HugeImages\Processing\ProcessingExtensions.cs:line 25
   at GameRealisticMap.Arma3.Imagery.IdMapRenderBase`1.Render(IArma3MapConfig config, IContext context) in D:\a\ArmaRealMap\ArmaRealMap\GameRealisticMap.Arma3\Imagery\IdMapRenderBase.cs:line 43
   at GameRealisticMap.Arma3.Imagery.ImagerySource.CreateIdMap() in D:\a\ArmaRealMap\ArmaRealMap\GameRealisticMap.Arma3\Imagery\ImagerySource.cs:line 28
   at GameRealisticMap.Arma3.GameEngine.ImageryCompiler.Compile(IArma3MapConfig config, IImagerySource source) in D:\a\ArmaRealMap\ArmaRealMap\GameRealisticMap.Arma3\GameEngine\ImageryCompiler.cs:line 58
   at GameRealisticMap.Arma3.Arma3MapGenerator.GenerateWrp(IProgressTask progress, Arma3MapConfig config, IContext context, ITerrainArea area, Arma3LayerGeneratorCatalog generators) in D:\a\ArmaRealMap\ArmaRealMap\GameRealisticMap.Arma3\Arma3MapGenerator.cs:line 140
   at GameRealisticMap.Arma3.Arma3MapGenerator.GenerateWrp(IProgressTask progress, Arma3MapConfig a3config, Boolean pngToPaa) in D:\a\ArmaRealMap\ArmaRealMap\GameRealisticMap.Arma3\Arma3MapGenerator.cs:line 99
   at GameRealisticMap.Arma3.Arma3MapGenerator.GenerateMod(IProgressTask progress, Arma3MapConfig a3config) in D:\a\ArmaRealMap\ArmaRealMap\GameRealisticMap.Arma3\Arma3MapGenerator.cs:line 61
   at GameRealisticMap.Studio.Modules.MapConfigEditor.ViewModels.MapConfigEditorViewModel.DoGenerateMod(IProgressTaskUI task) in D:\a\ArmaRealMap\ArmaRealMap\GameRealisticMap.Studio\Modules\MapConfigEditor\ViewModels\MapConfigEditorViewModel.cs:line 451
   at GameRealisticMap.Studio.Modules.Reporting.ViewModels.ProgressToolViewModel.DoRunTask(String name, Func`2 run, Boolean prompt) in D:\a\ArmaRealMap\ArmaRealMap\GameRealisticMap.Studio\Modules\Reporting\ViewModels\ProgressToolViewModel.cs:line 190
```

**Comment by jetelain** [comment]
It's caused by an aeroway path used to create a surface.
