### ISSUE TITLE
Roads.IgnoreSmall ArgumentException while trying to create terrain of Rio de Janeiro region

### ISSUE THREAD

**Issue by AlphaGarg** [jetelain/ArmaRealMap#267]
Coordinates of centre of map = -22.72274750819522, -43.36849316353547
Map size = 8192
Unit scale = 10 metres

Issue happened all three times I attempted this configuration. Experiment was done using the Microsoft Store build of the software.

Output stacktrace:
`** 'Roads.IgnoreSmall' done in 00:06:00.7043783
Exception: System.ArgumentException: Invalid number of points in LineString (found 1 - must be 0 or >= 2)
   at GameRealisticMap.Arma3.GameEngine.RoadsCompiler.SaveRoadsShp(IArma3MapConfig config, IReadOnlyCollection`1 roadsList)
   at GameRealisticMap.Arma3.GameEngine.RoadsCompiler.Write(IArma3MapConfig config, IReadOnlyCollection`1 roadsList)
   at GameRealisticMap.Arma3.Arma3MapGenerator.GenerateWrp(IProgressTask progress, Arma3MapConfig config, IContext context, ITerrainArea area, Arma3LayerGeneratorCatalog generators)
   at GameRealisticMap.Arma3.Arma3MapGenerator.GenerateWrp(IProgressTask progress, Arma3MapConfig a3config, Boolean pngToPaa)
   at GameRealisticMap.Arma3.Arma3MapGenerator.GenerateMod(IProgressTask progress, Arma3MapConfig a3config)
   at GameRealisticMap.Studio.Modules.MapConfigEditor.ViewModels.MapConfigEditorViewModel.DoGenerateMod(IProgressTaskUI task)
   at GameRealisticMap.Studio.Modules.Reporting.ViewModels.ProgressToolViewModel.DoRunTask(String name, Func`2 run, Boolean prompt)
Memory: Peak: 3.524 G, System: 20.000 G
ERROR: Invalid number of points in LineString (found 1 - must be 0 or >= 2)
Task FAILED after 2068,6 seconds`

**Comment by jetelain** [comment]
Hi, it was likely fixed by #241. But with this change, many more roads are processed, making the generation process much more longer. (Roads Merge operation takes 1 hour now).

Please note that 80x80 Km with an urban area is probably not viable for Arma 3, map will requires very large amount of memory for players.

To ensure that this error wont happen again, I will add a safe guard to prevent it.
