### ISSUE TITLE
Generate Mod for Arma 3 Error

### ISSUE THREAD

**Issue by Dabako** [jetelain/ArmaRealMap#37]
Hey there, 
Nice to see that this project is still ongoing.
I am trying to generate a small map from east germany.
In the last step, generating the map with Mikos Tools. It aborts with that error. 
Probably not a bug of this tool? If yes then I am really sorry. Found after some search nothing to much helpful

```
<building a land class list from unbinarised wrp contents>
.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.C.C.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.
***warning***a3\structures_f_enoch\industrial\houses\factory_02_f.p3d:indexed lod 7: Named selection 'door_1_trigger ' has trailing space(s)
warnings are errors

factory_02_f.p3d Error(s) detected
```

```
**** Begin 'PboProject' (1 items to process)
C:\Program Files (x86)\Mikero\DePboTools\bin\pboProject.exe -E="arma3" +N -W -P -M="C:\Users\username\Documents\GameRealisticMap\Arma3\Mods\@m_32upd449580s184" "P:\z\arm\addons\m_32upd449580s184"
\z\arm\addons\m_32upd449580s184\config.cpp
class CfgPatches
{
class arm_m_32upd449580s184
{
units[] = {};
weapons[] = {};
requiredVersion = 1;
requiredAddons[] = { "arm_centraleurope" };
};
};
class CfgWorldList
{
class m_32upd449580s184{};
};
class CfgWorlds
{
class arm_world_centraleurope;
class m_32upd449580s184: arm_world_centraleurope
...

...
** 'PboProject' done in 00:00:01.9346773
Exception: System.ApplicationException: PboProject exited with code 1.
   at GameRealisticMap.Arma3.Arma3ToolsHelper.BuildWithMikeroPboProject(String pboPrefix, String targetMod, IProgressSystem progress)
   at GameRealisticMap.Arma3.GameEngine.PboProject.BinarizeAndCreatePbo(Arma3MapConfig config, IReadOnlyCollection`1 usedModels, IReadOnlyCollection`1 usedRvmat)
   at GameRealisticMap.Arma3.Arma3MapGenerator.GenerateMod(IProgressTask progress, Arma3MapConfig a3config)
   at GameRealisticMap.Studio.Modules.MapConfigEditor.ViewModels.MapConfigEditorViewModel.DoGenerateMod(IProgressTaskUI task)
   at GameRealisticMap.Studio.Modules.Reporting.ViewModels.ProgressToolViewModel.DoRunTask(String name, Func`2 run)
ERROR: PboProject exited with code 1.
Task FAILED after 540.8 seconds
ERROR: PboProject exited with code 1.
Task FAILED after 540.8 seconds
```

**Comment by Dabako** [comment]
Just as I thought removing the factory_02_f altogether did fix it. Wanted that to stay here nonetheless because maybe somone has the same error.

**Comment by jetelain** [comment]
Hi, Last version (released today) is no more based by default on pboProject and will avoid this kind of issue

**Comment by jetelain** [comment]
The issue is an "error" in a game file, mikero toolchain is not really tolerant and block it by default.
